import SwiftUI

extension L10n {
    static let english: [String: String] = [
        "addSubscription": "Add Subscription",
        "editSubscription": "Edit Subscription",
        "cancel": "Cancel",
        "close": "Close",
        "save": "Save",
        "details": "Details",
        "name": "Name",
        "amount": "Amount",
        "currency": "Currency",
        "nextPayment": "Next payment",
        "trialPeriod": "Trial period",
        "trialEnabled": "Trial",
        "trialStart": "From",
        "trialEnd": "To",
        "trialHint": "Charges start after the trial end date.",
        "needTrialRange": "valid trial dates",
        "today": "Today",
        "period": "Period",
        "organization": "Organization",
        "category": "Category",
        "paymentMethod": "Payment method",
        "icon": "Icon",
        "notes": "Notes",
        "active": "Active",
        "requiredTitle": "Required fields",
        "needName": "name",
        "needAmount": "amount",
        "needDate": "valid payment date",
        "requiredPrefix": "Fill in",
        "dateHint": "Use date format YYYY-MM-DD.",
        "settings": "Settings",
        "account": "Account",
        "data": "iCloud & Data",
        "localPlaceholder": "Local-only placeholder",
        "preferences": "Preferences",
        "baseCurrency": "Base currency",
        "exchangeRates": "CBR rates",
        "exchangeFallback": "fallback rates",
        "refresh": "Refresh",
        "updated": "updated",
        "itemsCountFormat": "%d items",
        "addCategory": "Add Category",
        "categoryName": "Category name",
        "popularCategories": "Popular categories",
        "chooseEmoji": "Choose emoji",
        "categoryAdded": "Category added.",
        "addPaymentMethod": "Add Payment Method",
        "paymentMethodName": "Payment method name",
        "paymentMethodType": "Type",
        "last4Optional": "Last 4 digits (optional)",
        "chooseColor": "Choose color",
        "paymentTypeCustom": "Custom",
        "paymentTypeWallet": "Wallet",
        "paymentTypeDebit": "Debit Card",
        "paymentTypeCredit": "Credit Card",
        "paymentTypeBank": "Bank",
        "paymentTypeCash": "Cash",
        "paymentMethodAdded": "Payment method added.",
        "paymentMethodAlreadyExists": "A payment method with this name already exists.",
        "firstReminderTitle": "First reminder",
        "secondReminderTitle": "Second reminder",
        "daysBeforeFormat": "%d days before",
        "rounding": "Rounding",
        "compactNumbers": "Compact numbers",
        "categories": "Categories",
        "paymentMethods": "Payment Methods",
        "reminders": "Reminders",
        "firstReminder": "First reminder: %d day before",
        "secondReminder": "Second reminder: %d days before",
        "sendTestNotification": "Send Test Notification",
        "syncRemindersApp": "Sync with Reminders",
        "openRemindersApp": "Open Reminders",
        "remindersSyncDone": "Synced %d active subscriptions to Reminders.",
        "remindersAccessDenied": "Reminders access denied.",
        "remindersSyncFailed": "Could not sync with Reminders.",
        "appearance": "Appearance",
        "mode": "Mode",
        "accent": "Accent",
        "softNeumorphicPreviewTitle": "Soft Neumorphic",
        "softNeumorphicPreviewSubtitle": "Raised cards, inset controls, light tactile surfaces",
        "language": "Language",
        "haptic": "Haptic feedback",
        "about": "About",
        "aboutSubPulse": "About SubPulse",
        "product": "Product",
        "version": "Version",
        "developer": "Developer",
        "bundleIdentifier": "Bundle ID",
        "localFirst": "Local on this Mac",
        "aboutTagline": "A calm subscription calendar for the family budget.",
        "aboutText": "A local-first subscription calendar for macOS.",
        "aboutImportText": "Screenshot/text import uses local text recognition for screenshots or copied subscription text. Review recognized names and prices before saving.",
        "exportBackup": "Export Backup",
        "restoreBackup": "Restore Backup",
        "backupExportedFormat": "Backup exported: %@",
        "backupExportFailed": "Could not export backup.",
        "backupRestoredFormat": "Backup restored. Subscriptions: %d.",
        "backupRestoreFailed": "Could not restore this backup.",
        "restoreBackupTitle": "Restore from backup?",
        "restoreBackupMessage": "Current SubPulse data will be replaced by the selected backup file.",
        "restoreBackupConfirm": "Restore Backup",
        "dangerZone": "Danger Zone",
        "resetAll": "Reset All",
        "resetAllHint": "Deletes subscriptions, categories, payment methods, reminders and returns preferences to defaults.",
        "resetAllTitle": "Reset all SubPulse data?",
        "resetAllMessage": "This will delete all subscriptions and restore demo data. This action cannot be undone.",
        "resetAllConfirm": "Reset Everything",
        "resetAllDone": "SubPulse has been reset.",
        "resetAllFailed": "Could not reset SubPulse data.",
        "remindersResetDone": "SubPulse reminders were removed.",
        "dashboard": "All Subs",
        "calendar": "Calendar",
        "subscriptions": "Subscriptions",
        "analytics": "Analytics"
        ,
        "regularMonth": "Regular Month",
        "search": "Search",
        "searchSubscriptions": "Search subscriptions",
        "searchSubscriptionsHint": "Find renewals by service, category, currency or payment method.",
        "searchNoResults": "No matching subscriptions.",
        "searchResultsFormat": "%d results",
        "stats": "Stats",
        "filter": "Filter",
        "sort": "Sort",
        "edit": "Edit",
        "archive": "Archive",
        "activate": "Activate",
        "delete": "Delete",
        "archived": "Archived",
        "noPaymentMethod": "No payment method",
        "payments": "payments",
        "noPayments": "No payments",
        "noPaymentsDescription": "Nothing renews on this day.",
        "dueToday": "Due today",
        "nextRenewalInDays": "Next in %d days",
        "renewalsThisMonthFormat": "%d renewals this month",
        "spendIntelligence": "Spend Intelligence",
        "spendSubtitle": "A clean forecast for renewals, categories, and the pulse of your recurring costs.",
        "projectedYearlySpend": "projected yearly spend",
        "year": "Year",
        "allCategories": "All categories",
        "yearlyForecast": "Yearly forecast",
        "periodForecast": "Forecast",
        "periodOneMonth": "1 month",
        "periodSixMonths": "6 months",
        "periodOneYear": "1 year",
        "averageMonth": "Average month",
        "activeSubs": "Active subs"
        ,
        "weekly": "Weekly",
        "monthly": "Monthly",
        "yearly": "Yearly",
        "custom": "Custom",
        "activeFilter": "Active",
        "archivedFilter": "Archived",
        "allFilter": "All",
        "dateSort": "Date",
        "amountSort": "Amount",
        "nameSort": "Name",
        "none": "None",
        "placeholder": "Placeholder",
        "upcoming": "Upcoming",
        "categoryMix": "Category Mix",
        "perYear": "per year",
        "breakdown": "Breakdown",
        "monthlyProjection": "Monthly Projection",
        "monthlyProjectionDescription": "Expected renewals across the selected period",
        "mostExpensiveSubscription": "Most expensive subscription",
        "mostExpensiveCategory": "Most expensive category",
        "savingPotential": "Saving potential",
        "disableServicesFormat": "Disable %@",
        "needTwoServices": "Add at least two active services",
        "noData": "No data",
        "addActiveSubscriptions": "Add active subscriptions to see insights.",
        "upcomingCharges": "Upcoming charges",
        "nextWindows": "Next 7 / 14 / 30 days",
        "nextDaysFormat": "Next %d days",
        "chargesCountFormat": "%d charges",
        "spendGrowth": "Spend growth",
        "monthComparison": "Selected period vs previous period",
        "currentMonth": "Current period",
        "previousMonth": "Previous month",
        "previousPeriod": "Previous period",
        "growthUpFormat": "Up %@ (%@)",
        "growthDownFormat": "Down %@ (%@)",
        "growthNoPreviousFormat": "New monthly spend: %@",
        "growthFlat": "No change this month.",
        "newSubscriptionsImpactFormat": "%d new subscriptions add %@ in this period.",
        "topSubscriptions": "Top subscriptions",
        "annualRanking": "Annual cost ranking",
        "periodRanking": "Cost ranking for selected period",
        "forgottenRisk": "Forgotten risk",
        "forgottenRiskDescription": "Old, costly, manual or undocumented services",
        "noRiskFound": "No obvious forgotten-subscription risk.",
        "riskOld": "old",
        "riskExpensive": "expensive",
        "riskNoNotes": "no notes",
        "riskManual": "manual period",
        "savingScenarios": "Saving scenarios",
        "savingScenariosDescription": "What happens if you turn services off",
        "annualSaving": "annual saving",
        "periodSaving": "saving in selected period",
        "healthScore": "Subscription Health Score",
        "healthScoreSubtitle": "One quick read on duplicates, costly services, forgotten risks and savings potential.",
        "healthNoData": "No data",
        "healthExcellent": "Clean",
        "healthGood": "Good",
        "healthNeedsAttention": "Needs attention",
        "healthDuplicatesFormat": "%d duplicates",
        "healthExpensiveFormat": "%d costly",
        "healthRisksFormat": "%d risks",
        "healthSavingsFormat": "save %@",
        "other": "Other",
        "paymentMethodMissing": "No payment method",
        "next": "next"
        ,
        "automaticImportFrom": "Import from:",
        "screenshotTextImportSource": "Screenshot/Text",
        "activeImport": "Active",
        "appStoreImportTitle": "Import from screenshot/text",
        "appStoreImportSubtitle": "Choose a screenshot or paste subscription text, then confirm recognized prices.",
        "chooseAppStoreScreenshot": "Choose screenshot",
        "recognizeSubscriptions": "Recognize text and prices",
        "pasteAppStoreText": "Paste subscription text here, or choose a screenshot from a subscription screen.",
        "recognizedSubscriptions": "Recognized subscriptions",
        "selectedCountFormat": "%d selected",
        "noRecognizedSubscriptions": "Nothing recognized yet",
        "appStoreImportEmptyHint": "Use a screenshot or paste text with service names and prices.",
        "importSelected": "Import selected",
        "alreadyExists": "Already exists",
        "recognitionFailed": "Could not recognize text in this image.",
        "noImportText": "No subscription names and prices were found. Try a clearer screenshot or paste text manually.",
        "importedFromAppStoreOCR": "Imported from local screenshot/text recognition.",
        "popularServices": "Popular services",
        "allServices": "All services",
        "searchServices": "Search services",
        "fileImport": "File",
        "customSubscription": "Custom",
        "dataMode": "Data",
        "fullyFree": "Fully free, local-first MVP",
        "notificationsReady": "Notifications are ready.",
        "persistenceErrorTitle": "Could not save changes",
        "saveFailedMessage": "SubPulse could not save this change. Please try again.",
        "importSaveFailedMessage": "SubPulse could not save imported subscriptions. Please try again.",
        "deleteFailedMessage": "SubPulse could not delete this subscription. Please try again.",
        "dayDetails": "Day details",
        "chooseSubscription": "Choose a subscription",
        "emptyDayHint": "No renewals yet. Add one for this date.",
        "subscriptionDetails": "Subscription details"
    ]

    static let russian: [String: String] = [
        "addSubscription": "Добавить подписку",
        "editSubscription": "Редактировать подписку",
        "cancel": "Отмена",
        "close": "Закрыть",
        "save": "Сохранить",
        "details": "Детали",
        "name": "Название",
        "amount": "Сумма",
        "currency": "Валюта",
        "nextPayment": "Следующий платеж",
        "trialPeriod": "Пробный период",
        "trialEnabled": "Trial",
        "trialStart": "С",
        "trialEnd": "До",
        "trialHint": "Списания начнутся после окончания пробного периода.",
        "needTrialRange": "корректные даты trial",
        "today": "Сегодня",
        "period": "Период",
        "organization": "Организация",
        "category": "Категория",
        "paymentMethod": "Способ оплаты",
        "icon": "Иконка",
        "notes": "Заметки",
        "active": "Активна",
        "requiredTitle": "Обязательные поля",
        "needName": "название",
        "needAmount": "сумма",
        "needDate": "корректная дата платежа",
        "requiredPrefix": "Заполните",
        "dateHint": "Используйте формат даты YYYY-MM-DD.",
        "settings": "Настройки",
        "account": "Аккаунт",
        "data": "iCloud и данные",
        "localPlaceholder": "Пока только локально",
        "preferences": "Параметры",
        "baseCurrency": "Основная валюта",
        "exchangeRates": "Курс ЦБ РФ",
        "exchangeFallback": "резервный курс",
        "refresh": "Обновить",
        "updated": "обновлено",
        "itemsCountFormat": "%d элементов",
        "addCategory": "Добавить категорию",
        "categoryName": "Название категории",
        "popularCategories": "Популярные категории",
        "chooseEmoji": "Выберите emoji",
        "categoryAdded": "Категория добавлена.",
        "addPaymentMethod": "Добавить способ оплаты",
        "paymentMethodName": "Название способа оплаты",
        "paymentMethodType": "Тип",
        "last4Optional": "Последние 4 цифры (необязательно)",
        "chooseColor": "Выберите цвет",
        "paymentTypeCustom": "Свой",
        "paymentTypeWallet": "Кошелёк",
        "paymentTypeDebit": "Дебетовая карта",
        "paymentTypeCredit": "Кредитная карта",
        "paymentTypeBank": "Банк",
        "paymentTypeCash": "Наличные",
        "paymentMethodAdded": "Способ оплаты добавлен.",
        "paymentMethodAlreadyExists": "Способ оплаты с таким названием уже есть.",
        "firstReminderTitle": "Первое напоминание",
        "secondReminderTitle": "Второе напоминание",
        "daysBeforeFormat": "за %d дней",
        "rounding": "Округление",
        "compactNumbers": "Компактные числа",
        "categories": "Категории",
        "paymentMethods": "Способы оплаты",
        "reminders": "Напоминания",
        "firstReminder": "Первое напоминание: за %d день",
        "secondReminder": "Второе напоминание: за %d дней",
        "sendTestNotification": "Отправить тестовое уведомление",
        "syncRemindersApp": "Синхронизировать с Reminders",
        "openRemindersApp": "Открыть Reminders",
        "remindersSyncDone": "Синхронизировано активных подписок: %d.",
        "remindersAccessDenied": "Доступ к Reminders запрещён.",
        "remindersSyncFailed": "Не удалось синхронизировать с Reminders.",
        "appearance": "Оформление",
        "mode": "Тема",
        "accent": "Акцент",
        "softNeumorphicPreviewTitle": "Soft Neumorphic",
        "softNeumorphicPreviewSubtitle": "Выпуклые карточки, утопленные контролы и мягкие светлые поверхности",
        "language": "Язык",
        "haptic": "Тактильный отклик",
        "about": "О приложении",
        "aboutSubPulse": "О SubPulse",
        "product": "Продукт",
        "version": "Версия",
        "developer": "Разработчик",
        "bundleIdentifier": "Bundle ID",
        "localFirst": "Локально на этом Mac",
        "aboutTagline": "Спокойный календарь подписок для семейного бюджета.",
        "aboutText": "Локальный календарь подписок для macOS.",
        "aboutImportText": "Импорт со скриншота/текста использует локальное распознавание текста на скриншоте или скопированном тексте подписок. Проверяйте названия и цены перед сохранением.",
        "exportBackup": "Экспорт бэкапа",
        "restoreBackup": "Восстановить бэкап",
        "backupExportedFormat": "Бэкап экспортирован: %@",
        "backupExportFailed": "Не удалось экспортировать бэкап.",
        "backupRestoredFormat": "Бэкап восстановлен. Подписок: %d.",
        "backupRestoreFailed": "Не удалось восстановить этот бэкап.",
        "restoreBackupTitle": "Восстановить из бэкапа?",
        "restoreBackupMessage": "Текущие данные SubPulse будут заменены выбранным файлом бэкапа.",
        "restoreBackupConfirm": "Восстановить бэкап",
        "dangerZone": "Опасная зона",
        "resetAll": "Сбросить всё",
        "resetAllHint": "Удаляет подписки, категории, способы оплаты, напоминания и возвращает настройки по умолчанию.",
        "resetAllTitle": "Сбросить все данные SubPulse?",
        "resetAllMessage": "Все подписки будут удалены, затем приложение восстановит демо-данные. Это действие нельзя отменить.",
        "resetAllConfirm": "Сбросить всё",
        "resetAllDone": "SubPulse сброшен.",
        "resetAllFailed": "Не удалось сбросить данные SubPulse.",
        "remindersResetDone": "Напоминания SubPulse удалены.",
        "dashboard": "Все подписки",
        "calendar": "Календарь",
        "subscriptions": "Подписки",
        "analytics": "Аналитика"
        ,
        "regularMonth": "Обычный месяц",
        "search": "Поиск",
        "searchSubscriptions": "Поиск подписок",
        "searchSubscriptionsHint": "Ищите списания по сервису, категории, валюте или способу оплаты.",
        "searchNoResults": "Подходящих подписок нет.",
        "searchResultsFormat": "%d результатов",
        "stats": "Статистика",
        "filter": "Фильтр",
        "sort": "Сортировка",
        "edit": "Изменить",
        "archive": "Архивировать",
        "activate": "Активировать",
        "delete": "Удалить",
        "archived": "В архиве",
        "noPaymentMethod": "Нет способа оплаты",
        "payments": "платежей",
        "noPayments": "Нет платежей",
        "noPaymentsDescription": "В этот день ничего не списывается.",
        "dueToday": "Списание сегодня",
        "nextRenewalInDays": "Следующее через %d дн.",
        "renewalsThisMonthFormat": "%d списаний в месяце",
        "spendIntelligence": "Аналитика расходов",
        "spendSubtitle": "Прогноз продлений, категорий и регулярных расходов.",
        "projectedYearlySpend": "прогноз расходов за год",
        "year": "Год",
        "allCategories": "Все категории",
        "yearlyForecast": "Прогноз за год",
        "periodForecast": "Прогноз",
        "periodOneMonth": "1 месяц",
        "periodSixMonths": "6 месяцев",
        "periodOneYear": "1 год",
        "averageMonth": "В среднем за месяц",
        "activeSubs": "Активных подписок"
        ,
        "weekly": "Еженедельно",
        "monthly": "Ежемесячно",
        "yearly": "Ежегодно",
        "custom": "Вручную",
        "activeFilter": "Активные",
        "archivedFilter": "Архив",
        "allFilter": "Все",
        "dateSort": "Дата",
        "amountSort": "Сумма",
        "nameSort": "Название",
        "none": "Нет",
        "placeholder": "Заглушка",
        "upcoming": "Ближайшие",
        "categoryMix": "Категории",
        "perYear": "в год",
        "breakdown": "Разбивка",
        "monthlyProjection": "Прогноз по месяцам",
        "monthlyProjectionDescription": "Ожидаемые списания в выбранном периоде",
        "mostExpensiveSubscription": "Самая дорогая подписка",
        "mostExpensiveCategory": "Самая дорогая категория",
        "savingPotential": "Потенциал экономии",
        "disableServicesFormat": "Отключить %@",
        "needTwoServices": "Добавьте минимум два активных сервиса",
        "noData": "Нет данных",
        "addActiveSubscriptions": "Добавьте активные подписки, чтобы увидеть инсайты.",
        "upcomingCharges": "Ближайшие списания",
        "nextWindows": "Следующие 7 / 14 / 30 дней",
        "nextDaysFormat": "За %d дней",
        "chargesCountFormat": "%d списаний",
        "spendGrowth": "Рост расходов",
        "monthComparison": "Выбранный период против предыдущего",
        "currentMonth": "Текущий период",
        "previousMonth": "Прошлый месяц",
        "previousPeriod": "Прошлый период",
        "growthUpFormat": "Рост на %@ (%@)",
        "growthDownFormat": "Снижение на %@ (%@)",
        "growthNoPreviousFormat": "Новый месячный расход: %@",
        "growthFlat": "В этом месяце без изменений.",
        "newSubscriptionsImpactFormat": "%d новых подписок добавляют %@ за этот период.",
        "topSubscriptions": "Топ подписок",
        "annualRanking": "Рейтинг по годовой стоимости",
        "periodRanking": "Рейтинг по стоимости за выбранный период",
        "forgottenRisk": "Риск забытых подписок",
        "forgottenRiskDescription": "Старые, дорогие, ручные или без заметок",
        "noRiskFound": "Явных рисков забытых подписок нет.",
        "riskOld": "давно создана",
        "riskExpensive": "дорогая",
        "riskNoNotes": "нет заметок",
        "riskManual": "ручной период",
        "savingScenarios": "Сценарии экономии",
        "savingScenariosDescription": "Что будет, если отключить сервисы",
        "annualSaving": "экономия в год",
        "periodSaving": "экономия за выбранный период",
        "healthScore": "Индекс здоровья подписок",
        "healthScoreSubtitle": "Быстрая оценка дублей, дорогих сервисов, забытых рисков и потенциала экономии.",
        "healthNoData": "Нет данных",
        "healthExcellent": "Чисто",
        "healthGood": "Хорошо",
        "healthNeedsAttention": "Нужно внимание",
        "healthDuplicatesFormat": "%d дублей",
        "healthExpensiveFormat": "%d дорогих",
        "healthRisksFormat": "%d рисков",
        "healthSavingsFormat": "сэкономить %@",
        "other": "Другое",
        "paymentMethodMissing": "Способ оплаты не указан",
        "next": "следующий платеж"
        ,
        "automaticImportFrom": "Импорт из:",
        "screenshotTextImportSource": "Скриншот/текст",
        "activeImport": "Активно",
        "appStoreImportTitle": "Импорт со скриншота/текста",
        "appStoreImportSubtitle": "Выберите скриншот или вставьте текст подписок, затем подтвердите распознанные цены.",
        "chooseAppStoreScreenshot": "Выбрать скриншот",
        "recognizeSubscriptions": "Распознать текст и суммы",
        "pasteAppStoreText": "Вставьте сюда текст подписок или выберите скриншот экрана подписок.",
        "recognizedSubscriptions": "Распознанные подписки",
        "selectedCountFormat": "выбрано: %d",
        "noRecognizedSubscriptions": "Пока ничего не распознано",
        "appStoreImportEmptyHint": "Используйте скриншот или вставьте текст с названиями сервисов и ценами.",
        "importSelected": "Добавить выбранные",
        "alreadyExists": "Уже есть",
        "recognitionFailed": "Не удалось распознать текст на изображении.",
        "noImportText": "Не нашел названия подписок и суммы. Попробуйте более четкий скриншот или вставьте текст вручную.",
        "importedFromAppStoreOCR": "Импортировано через локальное распознавание скриншота/текста.",
        "popularServices": "Популярные сервисы",
        "allServices": "Все сервисы",
        "searchServices": "Поиск сервисов",
        "fileImport": "Файл",
        "customSubscription": "Своя",
        "dataMode": "Данные",
        "fullyFree": "Полностью бесплатно, локально на Mac",
        "notificationsReady": "Уведомления готовы.",
        "persistenceErrorTitle": "Не удалось сохранить изменения",
        "saveFailedMessage": "SubPulse не смог сохранить изменение. Попробуйте еще раз.",
        "importSaveFailedMessage": "SubPulse не смог сохранить импортированные подписки. Попробуйте еще раз.",
        "deleteFailedMessage": "SubPulse не смог удалить подписку. Попробуйте еще раз.",
        "dayDetails": "Детали дня",
        "chooseSubscription": "Выбрать подписку",
        "emptyDayHint": "На этот день ещё нет списаний. Добавьте подписку на эту дату.",
        "subscriptionDetails": "Детали подписки"
    ]

    static let russianCategoryNames: [String: String] = [
        "Streaming": "Стриминг",
        "Music": "Музыка",
        "Cloud Storage": "Облачное хранилище",
        "Storage": "Хранилище",
        "AI Tools": "AI-инструменты",
        "Productivity": "Продуктивность",
        "Software": "Программы",
        "Gaming": "Игры",
        "News & Media": "Новости и медиа",
        "Fitness": "Фитнес",
        "Finance": "Финансы",
        "Education": "Обучение",
        "Security": "Безопасность",
        "Utilities": "Утилиты",
        "Family": "Семья",
        "Other": "Другое"
    ]

    static let englishPaymentMethodNames: [String: String] = [
        "applepay": "Apple Pay",
        "googlepay": "Google Pay",
        "дебетоваякарта": "Debit Card",
        "debitcard": "Debit Card",
        "кредитнаякарта": "Credit Card",
        "creditcard": "Credit Card"
    ]

    static let russianPaymentMethodNames: [String: String] = [
        "applepay": "Apple Pay",
        "googlepay": "Google Pay",
        "дебетоваякарта": "Дебетовая карта",
        "debitcard": "Дебетовая карта",
        "кредитнаякарта": "Кредитная карта",
        "creditcard": "Кредитная карта"
    ]
}
